spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_service?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true